const data = {
    debtors: {
      items: [
            {
              debtorNumber: "0028396",
              name: "JB PEARL",
              client: "BRAG25",
              score: 0,
              clt_restricted_id: "N",
              account: "9403454",
              assigned: "112,063.50",
              principal_due: 112063.5,
              principalDue: 112063.5,
              intDue: 0,
              accruedInt: 0,
              invoiceInterestDue: 0,
              interestDue: 0,
              totalDueNoInterest: 112063.5,
              balance: "112,063.50",
              totalPastDue: "113,063.50",
              assignDate: "2022-12-21",
              reviewDate: "2021-04-10",
              disputeReviewDate: null,
              cashAppReviewDate: null,
              creditReviewDate: null,
              touched: 0,
              max_inv_past_due_bucket: 181,
              actionCode: "ANA",
              lastInteraction: "2022-12-22",
              status: "IAC",
              fullStatus: "INVOICES ARE CURRENT",
              desk: "007",
              deskName: "DELL TERMS NB",
              disputeStatus: "",
              disputeDesk: "",
              cashAppStatus: "",
              cashAppDesk: "",
              creditStatus: "",
              creditDesk: "",
              agency: "USD3",
              netInvestment: "",
              shipDate: null,
              currency: "USD"
            },
            {
              debtorNumber: "0028332",
              name: "TRIPLE H FARMS",
              client: "BRAG25",
              score: 0,
              clt_restricted_id: "N",
              account: "4638112",
              assigned: "81,046.00",
              principal_due: 81046,
              principalDue: 81046,
              intDue: 0,
              accruedInt: 0,
              invoiceInterestDue: 0,
              interestDue: 0,
              totalDueNoInterest: 81046,
              balance: "81,046.00",
              totalPastDue: "81,046.00",
              assignDate: "2022-12-21",
              reviewDate: "2021-04-10",
              disputeReviewDate: null,
              cashAppReviewDate: null,
              creditReviewDate: null,
              touched: 0,
              max_inv_past_due_bucket: 181,
              actionCode: "ANA",
              lastInteraction: "2022-12-22",
              status: "IAC",
              fullStatus: "INVOICES ARE CURRENT",
              desk: "007",
              deskName: "DELL TERMS NB",
              disputeStatus: "",
              disputeDesk: "",
              cashAppStatus: "",
              cashAppDesk: "",
              creditStatus: "",
              creditDesk: "",
              agency: "USD3",
              netInvestment: "",
              shipDate: null,
              currency: "USD"
            },
            {
              debtorNumber: "0028346",
              name: "CARL PERRY FARMS",
              client: "BRAG25",
              score: 0,
              clt_restricted_id: "N",
              account: "9208614",
              assigned: "61,660.00",
              principal_due: 61660,
              principalDue: 61660,
              intDue: 0,
              accruedInt: 0,
              invoiceInterestDue: 0,
              interestDue: 0,
              totalDueNoInterest: 61660,
              balance: "61,660.00",
              totalPastDue: "61,660.00",
              assignDate: "2022-12-21",
              reviewDate: "2021-04-10",
              disputeReviewDate: null,
              cashAppReviewDate: null,
              creditReviewDate: null,
              touched: 0,
              max_inv_past_due_bucket: 181,
              actionCode: "ANA",
              lastInteraction: "2023-03-03",
              status: "IAC",
              fullStatus: "INVOICES ARE CURRENT",
              desk: "007",
              deskName: "DELL TERMS NB",
              disputeStatus: "",
              disputeDesk: "",
              cashAppStatus: "",
              cashAppDesk: "",
              creditStatus: "",
              creditDesk: "",
              agency: "USD3",
              netInvestment: "",
              shipDate: null,
              currency: "USD"
            },
            {
              debtorNumber: "0028367",
              name: "BRIAN JORDAN",
              client: "BRAG25",
              score: 0,
              clt_restricted_id: "N",
              account: "9251230",
              assigned: "53,230.50",
              principal_due: 53230.5,
              principalDue: 53230.5,
              intDue: 0,
              accruedInt: 0,
              invoiceInterestDue: 0,
              interestDue: 0,
              totalDueNoInterest: 53230.5,
              balance: "53,230.50",
              totalPastDue: "53,230.50",
              assignDate: "2022-12-21",
              reviewDate: "2021-04-10",
              disputeReviewDate: null,
              cashAppReviewDate: null,
              creditReviewDate: null,
              touched: 0,
              max_inv_past_due_bucket: 181,
              actionCode: "ANA",
              lastInteraction: "2022-12-22",
              status: "IAC",
              fullStatus: "INVOICES ARE CURRENT",
              desk: "007",
              deskName: "DELL TERMS NB",
              disputeStatus: "",
              disputeDesk: "",
              cashAppStatus: "",
              cashAppDesk: "",
              creditStatus: "",
              creditDesk: "",
              agency: "USD3",
              netInvestment: "",
              shipDate: null,
              currency: "USD"
            },
            {
              debtorNumber: "0201429",
              name: "SEGREST FARMS",
              client: "BRAG25",
              score: 0,
              clt_restricted_id: "N",
              account: "9207546",
              assigned: "95,530.00",
              principal_due: 95530,
              principalDue: 95530,
              intDue: 0,
              accruedInt: 0,
              invoiceInterestDue: 0,
              interestDue: 0,
              totalDueNoInterest: 95530,
              balance: "95,530.00",
              totalPastDue: "95,530.00",
              assignDate: "2022-12-21",
              reviewDate: "2021-05-22",
              disputeReviewDate: null,
              cashAppReviewDate: null,
              creditReviewDate: null,
              touched: 0,
              max_inv_past_due_bucket: 181,
              actionCode: "ANA",
              lastInteraction: "2022-12-22",
              status: "IAC",
              fullStatus: "INVOICES ARE CURRENT",
              desk: "007",
              deskName: "DELL TERMS NB",
              disputeStatus: "",
              disputeDesk: "",
              cashAppStatus: "",
              cashAppDesk: "",
              creditStatus: "",
              creditDesk: "",
              agency: "USD3",
              netInvestment: "",
              shipDate: null,
              currency: "USD"
            }
        ],
        total: 5
    },
    debtorDetails: [
        {
            "debtorNumber": "0028332",
            "name1": "TRIPLE H FARMS",
            "clientId": "BRAG25",
            "clientName": "BAYER ROW CROPS",
            "clientLegalName": "LLC DBA Specialty Hybrids, Inc",
            "clientAddress": "800 N LINDBERGH BLVD",
            "clientAddress2": "MAILSTOP G5NH",
            "clientAddressState": "ST LOUIS MO",
            "clientZipCode": "63167",
            "agency": "USD3",
            "clt_class": "01",
            "currency": "USD",
            "clt_label_6_id": null,
            "cltLanguages": null,
            "account": "4638112",
            "status": "IAC",
            "fullStatus": "INVOICES ARE CURRENT",
            "desk": "007",
            "deskName": "DELL TERMS NB",
            "closeDate": null,
            "disputeStatus": "",
            "fullDisputeStatus": null,
            "cashAppStatus": "",
            "fullCashAppStatus": null,
            "creditStatus": "",
            "fullCreditStatus": null,
            "disputeDesk": "",
            "fullDisputeDesk": null,
            "cashAppDesk": "",
            "fullCashAppDesk": null,
            "creditDesk": "",
            "fullCreditDesk": null,
            "disputeReviewDate": null,
            "cashAppReviewDate": null,
            "creditReviewDate": null,
            "interestRate": "0.00%",
            "commissionRate": "0.00%",
            "commissionRule": 8,
            "assignFXRate": 1,
            "score": 0,
            "strategy": "",
            "tie_series": " ",
            "prediction": " ",
            "assignDate": "2022-12-21",
            "reviewDate": "2021-04-10",
            "daysForRecoveryCNHB": "2023-02-19",
            "lastChargeDate": null,
            "lastPaymentDate": null,
            "lastLetterDate": null,
            "lastWorkedDate": "2022-12-22",
            "lastTrustDate": null,
            "category": " ",
            "priority": " ",
            "assignedAmount": "$81,046.00",
            "totalReceived": "$0.00",
            "principal_due": 81046,
            "principalDue": "$81,046.00",
            "otherDue": "$0.00",
            "intDue": 0,
            "accruedInt": 0,
            "accruedInt18": 27737.71594520548,
            "interestDue": "$0.00",
            "interestDue18": 27737.71594520548,
            "invoiceInterestDue": 0,
            "totalDueNoInterest": 81046,
            "totalPastDue": "$81,046.00",
            "totalCurrentDue": "$0.00",
            "totalDue": "$81,046.00",
            "cbrFlag": "N",
            "adaFlag": " ",
            "misc1": "S9Hosbach",
            "misc2": "",
            "misc3": "",
            "misc4": "",
            "misc5": "",
            "misc6": "",
            "misc7": "",
            "misc8": "",
            "code1": "",
            "code2": "",
            "code3": "",
            "code4": "",
            "code5": "",
            "code6": "",
            "code7": "",
            "code8": "",
            "clientFullName": null,
            "date1": null,
            "date2": null,
            "date3": null,
            "date4": null,
            "dbrClass": "5",
            "invoiceTable": null,
            "detailStoreTarget": null,
            "widgetString": null,
            "stackWidget": [],
            "state": "AR",
            "contactName": "TRIPLE H FARMS",
            "contactPhone": "",
            "contactEmail": " ",
            "address": "   ",
            "accountCity": " ",
            "cityStateZip": " , AR  ",
            "zipCode": " ",
            "country": "USA",
            "zone": null,
            "warningZip": null,
            "invoiceList": "72147835,72163114,72178322,72200813,72214803,72221656,72226870,72227967",
            "tieSeries": " ",
            "parentAccount": "",
            "pendingTrust": "$0.00",
            "name2": null,
            "deskGroup": 239,
            "actionGroup": 81,
            "statusGroup": 64,
            "printWorkcard": "",
            "label1": "Bayer",
            "restrictedClientID": "N",
            "accCode": null,
            "dbr_action_queue_id": null,
            "actionMandatory": null,
            "clientEmailDailyContact": "bayerag@dandsltd.com",
            "clientEmailPtcVerification": "bayerag@dandsltd.com",
            "clientEmailSettlementRequest": "bayerag@dandsltd.com,MANDY.FISHER@DANDSLTD.COM",
            "clientEmailDisputeResolution": "bayerag@dandsltd.com",
            "clientEmailInvoiceBackup": "bayerag@dandsltd.com",
            "clientServiceEmail": "clientservices@dandsltd.com",
            "cltCustomNoteFlag": "N",
            "cltCustomNoteFlag2": "N",
            "cltLabel6Name": null,
            "paymentPortal": "",
            "legalJudgementDate": null,
            "legalPayoffDate": null,
            "enableCCP": 0,
            "lastWorkedDispute": null,
            "assignedDispute": null,
            "misc1Label": "",
            "misc2Label": "",
            "aemCount": 0,
            "agentPhone": "442036953190",
            "bucket0Due": "$0.00",
            "bucket30Due": "$0.00",
            "bucket60Due": "$0.00",
            "bucket90Due": "$0.00",
            "bucket120Due": "$0.00",
            "bucket180Due": "$0.00",
            "bucket181Due": "$81,046.00",
            "promiseAmount": "$0.00",
            "disputeAmount": "$0.00",
            "tz_timezone": null,
            "tz_spread": null,
            "tz_dst_offset": null,
            "tz_autumn_date": null,
            "tz_spring_date": null,
            "totalDueNumeric": 81046,
            "localTime": "",
            "dst": 0,
            "callWarning": false,
            "emailWarning": false,
            "jdReminder": false,
            "tiedList": "",
            "tiedAccounts": 0,
            "locked": false,
            "allowDispute": false,
            "clientServiceWidget": "clientServiceWidget",
            "disasterWarning": true,
            "showParentChildRelationship": true,
            "showGenerateButtons": true,
            "paymentMethod": "PTC",
            "showCylinders": false,
            "showLanguageTab": false,
            "halfFee": "Undefined",
            "showUpdatePid": false,
            "lockToOtherAgents": false,
            "dueInvoicesReport": false,
            "geAgingBlockCodedInvoices": false,
            "elsevierShowMoneyCrs": false,
            "showPoReqNoFilters": false,
            "showSmsButton": false,
            "showAllTiedHistory": true,
            "showCustomerNumberInTies": true,
            "crsTemplate": "3RDPARTY",
            "showDellRankPriority": false,
            "showHtmlSignature": false,
            "validateAlsInv": false,
            "bayahCrsButton": true,
            "legalInterestRate18": false,
            "showDispatchPrediction": false,
            "saveNotesOnSpecificTies": false,
            "showDellConsumerFilter": false,
            "callGrid8x8": false,
            "forceBasCode": false,
            "disableCSTicketsCreation": false,
            "projNo": ""
        },
        {
            "debtorNumber": "0028396",
            "name1": "JB PEARL",
            "clientId": "BRAG25",
            "clientName": "BAYER ROW CROPS",
            "clientLegalName": "LLC DBA Specialty Hybrids, Inc",
            "clientAddress": "800 N LINDBERGH BLVD",
            "clientAddress2": "MAILSTOP G5NH",
            "clientAddressState": "ST LOUIS MO",
            "clientZipCode": "63167",
            "agency": "USD3",
            "clt_class": "01",
            "currency": "USD",
            "clt_label_6_id": null,
            "cltLanguages": null,
            "account": "9403454",
            "status": "IAC",
            "fullStatus": "INVOICES ARE CURRENT",
            "desk": "007",
            "deskName": "DELL TERMS NB",
            "closeDate": null,
            "disputeStatus": "",
            "fullDisputeStatus": null,
            "cashAppStatus": "",
            "fullCashAppStatus": null,
            "creditStatus": "",
            "fullCreditStatus": null,
            "disputeDesk": "",
            "fullDisputeDesk": null,
            "cashAppDesk": "",
            "fullCashAppDesk": null,
            "creditDesk": "",
            "fullCreditDesk": null,
            "disputeReviewDate": null,
            "cashAppReviewDate": null,
            "creditReviewDate": null,
            "interestRate": "0.00%",
            "commissionRate": "0.00%",
            "commissionRule": 8,
            "assignFXRate": 1,
            "score": 0,
            "strategy": "",
            "tie_series": " ",
            "prediction": " ",
            "assignDate": "2022-12-21",
            "reviewDate": "2021-04-10",
            "daysForRecoveryCNHB": "2023-02-19",
            "lastChargeDate": null,
            "lastPaymentDate": null,
            "lastLetterDate": null,
            "lastWorkedDate": "2022-12-22",
            "lastTrustDate": null,
            "category": " ",
            "priority": " ",
            "assignedAmount": "$112,063.50",
            "totalReceived": "$0.00",
            "principal_due": 112063.5,
            "principalDue": "$112,063.50",
            "otherDue": "$0.00",
            "intDue": 0,
            "accruedInt": 0,
            "accruedInt18": 38353.34909589041,
            "interestDue": "$0.00",
            "interestDue18": 38353.34909589041,
            "invoiceInterestDue": 0,
            "totalDueNoInterest": 112063.5,
            "totalPastDue": "$112,063.50",
            "totalCurrentDue": "$0.00",
            "totalDue": "$112,063.50",
            "cbrFlag": "N",
            "adaFlag": " ",
            "misc1": "C1Goodyear",
            "misc2": "",
            "misc3": "",
            "misc4": "",
            "misc5": "",
            "misc6": "",
            "misc7": "",
            "misc8": "",
            "code1": "",
            "code2": "",
            "code3": "",
            "code4": "",
            "code5": "",
            "code6": "",
            "code7": "",
            "code8": "",
            "clientFullName": null,
            "date1": null,
            "date2": null,
            "date3": null,
            "date4": null,
            "dbrClass": "5",
            "invoiceTable": null,
            "detailStoreTarget": null,
            "widgetString": null,
            "stackWidget": [],
            "state": "KS",
            "contactName": "JB PEARL",
            "contactPhone": "7856170125",
            "contactEmail": " ",
            "address": "   ",
            "accountCity": " ",
            "cityStateZip": " , KS  ",
            "zipCode": " ",
            "country": "USA",
            "zone": null,
            "warningZip": null,
            "invoiceList": "72147415,72206251",
            "tieSeries": " ",
            "parentAccount": "",
            "pendingTrust": "$0.00",
            "name2": null,
            "deskGroup": 239,
            "actionGroup": 81,
            "statusGroup": 64,
            "printWorkcard": "",
            "label1": "Bayer",
            "restrictedClientID": "N",
            "accCode": null,
            "dbr_action_queue_id": null,
            "actionMandatory": null,
            "clientEmailDailyContact": "bayerag@dandsltd.com",
            "clientEmailPtcVerification": "bayerag@dandsltd.com",
            "clientEmailSettlementRequest": "bayerag@dandsltd.com,MANDY.FISHER@DANDSLTD.COM",
            "clientEmailDisputeResolution": "bayerag@dandsltd.com",
            "clientEmailInvoiceBackup": "bayerag@dandsltd.com",
            "clientServiceEmail": "clientservices@dandsltd.com",
            "cltCustomNoteFlag": "N",
            "cltCustomNoteFlag2": "N",
            "cltLabel6Name": null,
            "paymentPortal": "",
            "legalJudgementDate": null,
            "legalPayoffDate": null,
            "enableCCP": 0,
            "lastWorkedDispute": null,
            "assignedDispute": null,
            "misc1Label": "",
            "misc2Label": "",
            "aemCount": 0,
            "agentPhone": "442036953190",
            "bucket0Due": "$0.00",
            "bucket30Due": "$0.00",
            "bucket60Due": "$0.00",
            "bucket90Due": "$0.00",
            "bucket120Due": "$0.00",
            "bucket180Due": "$0.00",
            "bucket181Due": "$112,063.50",
            "promiseAmount": "$0.00",
            "disputeAmount": "$0.00",
            "tz_timezone": null,
            "tz_spread": null,
            "tz_dst_offset": null,
            "tz_autumn_date": null,
            "tz_spring_date": null,
            "totalDueNumeric": 112063.5,
            "localTime": "",
            "dst": 0,
            "callWarning": false,
            "emailWarning": false,
            "jdReminder": false,
            "tiedList": "",
            "tiedAccounts": 0,
            "locked": false,
            "allowDispute": false,
            "clientServiceWidget": "clientServiceWidget",
            "disasterWarning": true,
            "showParentChildRelationship": true,
            "showGenerateButtons": true,
            "paymentMethod": "PTC",
            "showCylinders": false,
            "showLanguageTab": false,
            "halfFee": "Undefined",
            "showUpdatePid": false,
            "lockToOtherAgents": false,
            "dueInvoicesReport": false,
            "geAgingBlockCodedInvoices": false,
            "elsevierShowMoneyCrs": false,
            "showPoReqNoFilters": false,
            "showSmsButton": false,
            "showAllTiedHistory": true,
            "showCustomerNumberInTies": true,
            "crsTemplate": "3RDPARTY",
            "showDellRankPriority": false,
            "showHtmlSignature": false,
            "validateAlsInv": false,
            "bayahCrsButton": true,
            "legalInterestRate18": false,
            "showDispatchPrediction": false,
            "saveNotesOnSpecificTies": false,
            "showDellConsumerFilter": false,
            "callGrid8x8": false,
            "forceBasCode": false,
            "disableCSTicketsCreation": false,
            "projNo": ""
        },
        {
            "debtorNumber": "0028346",
            "name1": "CARL PERRY FARMS",
            "clientId": "BRAG25",
            "clientName": "BAYER ROW CROPS",
            "clientLegalName": "LLC DBA Specialty Hybrids, Inc",
            "clientAddress": "800 N LINDBERGH BLVD",
            "clientAddress2": "MAILSTOP G5NH",
            "clientAddressState": "ST LOUIS MO",
            "clientZipCode": "63167",
            "agency": "USD3",
            "clt_class": "01",
            "currency": "USD",
            "clt_label_6_id": null,
            "cltLanguages": null,
            "account": "9208614",
            "status": "IAC",
            "fullStatus": "INVOICES ARE CURRENT",
            "desk": "007",
            "deskName": "DELL TERMS NB",
            "closeDate": null,
            "disputeStatus": "",
            "fullDisputeStatus": null,
            "cashAppStatus": "",
            "fullCashAppStatus": null,
            "creditStatus": "",
            "fullCreditStatus": null,
            "disputeDesk": "",
            "fullDisputeDesk": null,
            "cashAppDesk": "",
            "fullCashAppDesk": null,
            "creditDesk": "",
            "fullCreditDesk": null,
            "disputeReviewDate": null,
            "cashAppReviewDate": null,
            "creditReviewDate": null,
            "interestRate": "0.00%",
            "commissionRate": "0.00%",
            "commissionRule": 8,
            "assignFXRate": 1,
            "score": 0,
            "strategy": "",
            "tie_series": " ",
            "prediction": " ",
            "assignDate": "2022-12-21",
            "reviewDate": "2021-04-10",
            "daysForRecoveryCNHB": "2023-02-19",
            "lastChargeDate": null,
            "lastPaymentDate": null,
            "lastLetterDate": null,
            "lastWorkedDate": "2023-03-03",
            "lastTrustDate": null,
            "category": " ",
            "priority": " ",
            "assignedAmount": "$61,660.00",
            "totalReceived": "$0.00",
            "principal_due": 61660,
            "principalDue": "$61,660.00",
            "otherDue": "$0.00",
            "intDue": 0,
            "accruedInt": 0,
            "accruedInt18": 21102.923835616435,
            "interestDue": "$0.00",
            "interestDue18": 21102.923835616435,
            "invoiceInterestDue": 0,
            "totalDueNoInterest": 61660,
            "totalPastDue": "$61,660.00",
            "totalCurrentDue": "$0.00",
            "totalDue": "$61,660.00",
            "cbrFlag": "N",
            "adaFlag": " ",
            "misc1": "S9Hosbach",
            "misc2": "",
            "misc3": "",
            "misc4": "",
            "misc5": "",
            "misc6": "",
            "misc7": "",
            "misc8": "",
            "code1": "",
            "code2": "",
            "code3": "",
            "code4": "",
            "code5": "",
            "code6": "",
            "code7": "",
            "code8": "",
            "clientFullName": null,
            "date1": null,
            "date2": null,
            "date3": null,
            "date4": null,
            "dbrClass": "5",
            "invoiceTable": null,
            "detailStoreTarget": null,
            "widgetString": null,
            "stackWidget": [],
            "state": "GA",
            "contactName": "CARL PERRY FARMS",
            "contactPhone": "7062141447",
            "contactEmail": " ",
            "address": "   ",
            "accountCity": " ",
            "cityStateZip": " , GA  ",
            "zipCode": " ",
            "country": "USA",
            "zone": null,
            "warningZip": null,
            "invoiceList": "72147182,72155111,72170254",
            "tieSeries": " ",
            "parentAccount": "",
            "pendingTrust": "$0.00",
            "name2": null,
            "deskGroup": 239,
            "actionGroup": 81,
            "statusGroup": 64,
            "printWorkcard": "",
            "label1": "Bayer",
            "restrictedClientID": "N",
            "accCode": null,
            "dbr_action_queue_id": null,
            "actionMandatory": null,
            "clientEmailDailyContact": "bayerag@dandsltd.com",
            "clientEmailPtcVerification": "bayerag@dandsltd.com",
            "clientEmailSettlementRequest": "bayerag@dandsltd.com,MANDY.FISHER@DANDSLTD.COM",
            "clientEmailDisputeResolution": "bayerag@dandsltd.com",
            "clientEmailInvoiceBackup": "bayerag@dandsltd.com",
            "clientServiceEmail": "clientservices@dandsltd.com",
            "cltCustomNoteFlag": "N",
            "cltCustomNoteFlag2": "N",
            "cltLabel6Name": null,
            "paymentPortal": "",
            "legalJudgementDate": null,
            "legalPayoffDate": null,
            "enableCCP": 0,
            "lastWorkedDispute": null,
            "assignedDispute": null,
            "misc1Label": "",
            "misc2Label": "",
            "aemCount": 0,
            "agentPhone": "442036953190",
            "bucket0Due": "$0.00",
            "bucket30Due": "$0.00",
            "bucket60Due": "$0.00",
            "bucket90Due": "$0.00",
            "bucket120Due": "$0.00",
            "bucket180Due": "$0.00",
            "bucket181Due": "$61,660.00",
            "promiseAmount": "$0.00",
            "disputeAmount": "$0.00",
            "tz_timezone": null,
            "tz_spread": null,
            "tz_dst_offset": null,
            "tz_autumn_date": null,
            "tz_spring_date": null,
            "totalDueNumeric": 61660,
            "localTime": "",
            "dst": 0,
            "callWarning": false,
            "emailWarning": false,
            "jdReminder": false,
            "tiedList": "",
            "tiedAccounts": 0,
            "locked": false,
            "allowDispute": false,
            "clientServiceWidget": "clientServiceWidget",
            "disasterWarning": true,
            "showParentChildRelationship": true,
            "showGenerateButtons": true,
            "paymentMethod": "PTC",
            "showCylinders": false,
            "showLanguageTab": false,
            "halfFee": "Undefined",
            "showUpdatePid": false,
            "lockToOtherAgents": false,
            "dueInvoicesReport": false,
            "geAgingBlockCodedInvoices": false,
            "elsevierShowMoneyCrs": false,
            "showPoReqNoFilters": false,
            "showSmsButton": false,
            "showAllTiedHistory": true,
            "showCustomerNumberInTies": true,
            "crsTemplate": "3RDPARTY",
            "showDellRankPriority": false,
            "showHtmlSignature": false,
            "validateAlsInv": false,
            "bayahCrsButton": true,
            "legalInterestRate18": false,
            "showDispatchPrediction": false,
            "saveNotesOnSpecificTies": false,
            "showDellConsumerFilter": false,
            "callGrid8x8": false,
            "forceBasCode": false,
            "disableCSTicketsCreation": false,
            "projNo": ""
        },
        {
            "debtorNumber": "0028367",
            "name1": "BRIAN JORDAN",
            "clientId": "BRAG25",
            "clientName": "BAYER ROW CROPS",
            "clientLegalName": "LLC DBA Specialty Hybrids, Inc",
            "clientAddress": "800 N LINDBERGH BLVD",
            "clientAddress2": "MAILSTOP G5NH",
            "clientAddressState": "ST LOUIS MO",
            "clientZipCode": "63167",
            "agency": "USD3",
            "clt_class": "01",
            "currency": "USD",
            "clt_label_6_id": null,
            "cltLanguages": null,
            "account": "9251230",
            "status": "IAC",
            "fullStatus": "INVOICES ARE CURRENT",
            "desk": "007",
            "deskName": "DELL TERMS NB",
            "closeDate": null,
            "disputeStatus": "",
            "fullDisputeStatus": null,
            "cashAppStatus": "",
            "fullCashAppStatus": null,
            "creditStatus": "",
            "fullCreditStatus": null,
            "disputeDesk": "",
            "fullDisputeDesk": null,
            "cashAppDesk": "",
            "fullCashAppDesk": null,
            "creditDesk": "",
            "fullCreditDesk": null,
            "disputeReviewDate": null,
            "cashAppReviewDate": null,
            "creditReviewDate": null,
            "interestRate": "0.00%",
            "commissionRate": "0.00%",
            "commissionRule": 8,
            "assignFXRate": 1,
            "score": 0,
            "strategy": "",
            "tie_series": " ",
            "prediction": " ",
            "assignDate": "2022-12-21",
            "reviewDate": "2021-04-10",
            "daysForRecoveryCNHB": "2023-02-19",
            "lastChargeDate": null,
            "lastPaymentDate": null,
            "lastLetterDate": null,
            "lastWorkedDate": "2022-12-22",
            "lastTrustDate": null,
            "category": " ",
            "priority": " ",
            "assignedAmount": "$53,230.50",
            "totalReceived": "$0.00",
            "principal_due": 53230.5,
            "principalDue": "$53,230.50",
            "otherDue": "$0.00",
            "intDue": 0,
            "accruedInt": 0,
            "accruedInt18": 18217.956328767123,
            "interestDue": "$0.00",
            "interestDue18": 18217.956328767123,
            "invoiceInterestDue": 0,
            "totalDueNoInterest": 53230.5,
            "totalPastDue": "$53,230.50",
            "totalCurrentDue": "$0.00",
            "totalDue": "$53,230.50",
            "cbrFlag": "N",
            "adaFlag": " ",
            "misc1": "S5Turner",
            "misc2": "",
            "misc3": "",
            "misc4": "",
            "misc5": "",
            "misc6": "",
            "misc7": "",
            "misc8": "",
            "code1": "",
            "code2": "",
            "code3": "",
            "code4": "",
            "code5": "",
            "code6": "",
            "code7": "",
            "code8": "",
            "clientFullName": null,
            "date1": null,
            "date2": null,
            "date3": null,
            "date4": null,
            "dbrClass": "5",
            "invoiceTable": null,
            "detailStoreTarget": null,
            "widgetString": null,
            "stackWidget": [],
            "state": "IL",
            "contactName": "BRIAN JORDAN",
            "contactPhone": "8152919883",
            "contactEmail": " ",
            "address": "   ",
            "accountCity": " ",
            "cityStateZip": " , IL  ",
            "zipCode": " ",
            "country": "USA",
            "zone": null,
            "warningZip": null,
            "invoiceList": "72148181,72148182,72148451,72148453,72172241,72180458,72210103",
            "tieSeries": " ",
            "parentAccount": "",
            "pendingTrust": "$0.00",
            "name2": null,
            "deskGroup": 239,
            "actionGroup": 81,
            "statusGroup": 64,
            "printWorkcard": "",
            "label1": "Bayer",
            "restrictedClientID": "N",
            "accCode": null,
            "dbr_action_queue_id": null,
            "actionMandatory": null,
            "clientEmailDailyContact": "bayerag@dandsltd.com",
            "clientEmailPtcVerification": "bayerag@dandsltd.com",
            "clientEmailSettlementRequest": "bayerag@dandsltd.com,MANDY.FISHER@DANDSLTD.COM",
            "clientEmailDisputeResolution": "bayerag@dandsltd.com",
            "clientEmailInvoiceBackup": "bayerag@dandsltd.com",
            "clientServiceEmail": "clientservices@dandsltd.com",
            "cltCustomNoteFlag": "N",
            "cltCustomNoteFlag2": "N",
            "cltLabel6Name": null,
            "paymentPortal": "",
            "legalJudgementDate": null,
            "legalPayoffDate": null,
            "enableCCP": 0,
            "lastWorkedDispute": null,
            "assignedDispute": null,
            "misc1Label": "",
            "misc2Label": "",
            "aemCount": 0,
            "agentPhone": "442036953190",
            "bucket0Due": "$0.00",
            "bucket30Due": "$0.00",
            "bucket60Due": "$0.00",
            "bucket90Due": "$0.00",
            "bucket120Due": "$0.00",
            "bucket180Due": "$0.00",
            "bucket181Due": "$53,230.50",
            "promiseAmount": "$0.00",
            "disputeAmount": "$0.00",
            "tz_timezone": null,
            "tz_spread": null,
            "tz_dst_offset": null,
            "tz_autumn_date": null,
            "tz_spring_date": null,
            "totalDueNumeric": 53230.5,
            "localTime": "",
            "dst": 0,
            "callWarning": false,
            "emailWarning": false,
            "jdReminder": false,
            "tiedList": "",
            "tiedAccounts": 0,
            "locked": false,
            "allowDispute": false,
            "clientServiceWidget": "clientServiceWidget",
            "disasterWarning": true,
            "showParentChildRelationship": true,
            "showGenerateButtons": true,
            "paymentMethod": "PTC",
            "showCylinders": false,
            "showLanguageTab": false,
            "halfFee": "Undefined",
            "showUpdatePid": false,
            "lockToOtherAgents": false,
            "dueInvoicesReport": false,
            "geAgingBlockCodedInvoices": false,
            "elsevierShowMoneyCrs": false,
            "showPoReqNoFilters": false,
            "showSmsButton": false,
            "showAllTiedHistory": true,
            "showCustomerNumberInTies": true,
            "crsTemplate": "3RDPARTY",
            "showDellRankPriority": false,
            "showHtmlSignature": false,
            "validateAlsInv": false,
            "bayahCrsButton": true,
            "legalInterestRate18": false,
            "showDispatchPrediction": false,
            "saveNotesOnSpecificTies": false,
            "showDellConsumerFilter": false,
            "callGrid8x8": false,
            "forceBasCode": false,
            "disableCSTicketsCreation": false,
            "projNo": ""
        },
        {
            "debtorNumber": "0201429",
            "name1": "SEGREST FARMS",
            "clientId": "BRAG25",
            "clientName": "BAYER ROW CROPS",
            "clientLegalName": "LLC DBA Specialty Hybrids, Inc",
            "clientAddress": "800 N LINDBERGH BLVD",
            "clientAddress2": "MAILSTOP G5NH",
            "clientAddressState": "ST LOUIS MO",
            "clientZipCode": "63167",
            "agency": "USD3",
            "clt_class": "01",
            "currency": "USD",
            "clt_label_6_id": null,
            "cltLanguages": null,
            "account": "9207546",
            "status": "IAC",
            "fullStatus": "INVOICES ARE CURRENT",
            "desk": "007",
            "deskName": "DELL TERMS NB",
            "closeDate": null,
            "disputeStatus": "",
            "fullDisputeStatus": null,
            "cashAppStatus": "",
            "fullCashAppStatus": null,
            "creditStatus": "",
            "fullCreditStatus": null,
            "disputeDesk": "",
            "fullDisputeDesk": null,
            "cashAppDesk": "",
            "fullCashAppDesk": null,
            "creditDesk": "",
            "fullCreditDesk": null,
            "disputeReviewDate": null,
            "cashAppReviewDate": null,
            "creditReviewDate": null,
            "interestRate": "0.00%",
            "commissionRate": "0.00%",
            "commissionRule": 8,
            "assignFXRate": 1,
            "score": 0,
            "strategy": "",
            "tie_series": " ",
            "prediction": " ",
            "assignDate": "2022-12-21",
            "reviewDate": "2021-05-22",
            "daysForRecoveryCNHB": "2023-02-19",
            "lastChargeDate": null,
            "lastPaymentDate": null,
            "lastLetterDate": null,
            "lastWorkedDate": "2022-12-22",
            "lastTrustDate": null,
            "category": " ",
            "priority": " ",
            "assignedAmount": "$95,530.00",
            "totalReceived": "$0.00",
            "principal_due": 95530,
            "principalDue": "$95,530.00",
            "otherDue": "$0.00",
            "intDue": 0,
            "accruedInt": 0,
            "accruedInt18": 30716.166575342464,
            "interestDue": "$0.00",
            "interestDue18": 30716.166575342464,
            "invoiceInterestDue": 0,
            "totalDueNoInterest": 95530,
            "totalPastDue": "$95,530.00",
            "totalCurrentDue": "$0.00",
            "totalDue": "$95,530.00",
            "cbrFlag": "N",
            "adaFlag": " ",
            "misc1": "S9Hosbach",
            "misc2": "",
            "misc3": "",
            "misc4": "",
            "misc5": "",
            "misc6": "",
            "misc7": "",
            "misc8": "",
            "code1": "",
            "code2": "",
            "code3": "",
            "code4": "",
            "code5": "",
            "code6": "",
            "code7": "",
            "code8": "",
            "clientFullName": null,
            "date1": null,
            "date2": null,
            "date3": null,
            "date4": null,
            "dbrClass": "5",
            "invoiceTable": null,
            "detailStoreTarget": null,
            "widgetString": null,
            "stackWidget": [],
            "state": "AL",
            "contactName": "SEGREST FARMS",
            "contactPhone": "3347273919",
            "contactEmail": " ",
            "address": "   ",
            "accountCity": " ",
            "cityStateZip": " , AL  ",
            "zipCode": " ",
            "country": "USA",
            "zone": null,
            "warningZip": null,
            "invoiceList": "72222118,72222119",
            "tieSeries": " ",
            "parentAccount": "",
            "pendingTrust": "$0.00",
            "name2": null,
            "deskGroup": 239,
            "actionGroup": 81,
            "statusGroup": 64,
            "printWorkcard": "",
            "label1": "Bayer",
            "restrictedClientID": "N",
            "accCode": null,
            "dbr_action_queue_id": null,
            "actionMandatory": null,
            "clientEmailDailyContact": "bayerag@dandsltd.com",
            "clientEmailPtcVerification": "bayerag@dandsltd.com",
            "clientEmailSettlementRequest": "bayerag@dandsltd.com,MANDY.FISHER@DANDSLTD.COM",
            "clientEmailDisputeResolution": "bayerag@dandsltd.com",
            "clientEmailInvoiceBackup": "bayerag@dandsltd.com",
            "clientServiceEmail": "clientservices@dandsltd.com",
            "cltCustomNoteFlag": "N",
            "cltCustomNoteFlag2": "N",
            "cltLabel6Name": null,
            "paymentPortal": "",
            "legalJudgementDate": null,
            "legalPayoffDate": null,
            "enableCCP": 0,
            "lastWorkedDispute": null,
            "assignedDispute": null,
            "misc1Label": "",
            "misc2Label": "",
            "aemCount": 0,
            "agentPhone": "442036953190",
            "bucket0Due": "$0.00",
            "bucket30Due": "$0.00",
            "bucket60Due": "$0.00",
            "bucket90Due": "$0.00",
            "bucket120Due": "$0.00",
            "bucket180Due": "$0.00",
            "bucket181Due": "$95,530.00",
            "promiseAmount": "$0.00",
            "disputeAmount": "$0.00",
            "tz_timezone": null,
            "tz_spread": null,
            "tz_dst_offset": null,
            "tz_autumn_date": null,
            "tz_spring_date": null,
            "totalDueNumeric": 95530,
            "localTime": "",
            "dst": 0,
            "callWarning": false,
            "emailWarning": false,
            "jdReminder": false,
            "tiedList": "",
            "tiedAccounts": 0,
            "locked": false,
            "allowDispute": false,
            "clientServiceWidget": "clientServiceWidget",
            "disasterWarning": true,
            "showParentChildRelationship": true,
            "showGenerateButtons": true,
            "paymentMethod": "PTC",
            "showCylinders": false,
            "showLanguageTab": false,
            "halfFee": "Undefined",
            "showUpdatePid": false,
            "lockToOtherAgents": false,
            "dueInvoicesReport": false,
            "geAgingBlockCodedInvoices": false,
            "elsevierShowMoneyCrs": false,
            "showPoReqNoFilters": false,
            "showSmsButton": false,
            "showAllTiedHistory": true,
            "showCustomerNumberInTies": true,
            "crsTemplate": "3RDPARTY",
            "showDellRankPriority": false,
            "showHtmlSignature": false,
            "validateAlsInv": false,
            "bayahCrsButton": true,
            "legalInterestRate18": false,
            "showDispatchPrediction": false,
            "saveNotesOnSpecificTies": false,
            "showDellConsumerFilter": false,
            "callGrid8x8": false,
            "forceBasCode": false,
            "disableCSTicketsCreation": false,
            "projNo": ""
        }
    ],
    debtorNotes: {
      "0028396" : [
          {
            "date" : "2022-12-22 10:29",
            "user" : "EDI",
            "fullName" : null,
            "action" : " ",
            "fullAction" : null,
            "status" : "IAC",
            "fullStatus" : "INVOICES ARE CURRENT",
            "desk" : "007",
            "deskName" : "DELL TERMS NB",
            "noteSeqNo" : "000031",
            "dbr_no" : "0028396",
            "notes" : "Large Balance Fedex\n",
            "ltr_desc" : null,
            "ltr_code" : null,
            "dat_type" : "H"
          },
          {
            "date" : "2022-12-21 20:50",
            "user" : "EDI",
            "fullName" : null,
            "action" : "ANA",
            "fullAction" : "ADMIN NOTE ADDED",
            "status" : "IAC",
            "fullStatus" : "INVOICES ARE CURRENT",
            "desk" : "008",
            "deskName" : "DELL NT NEW BIZ",
            "noteSeqNo" : "000028",
            "dbr_no" : "0028396",
            "notes" : "Possible ties \n 8848072,7978990,7978927\n",
            "ltr_desc" : null,
            "ltr_code" : null,
            "dat_type" : "C"
          },
          {
            "date" : "2022-12-09 11:04",
            "user" : "EDI",
            "fullName" : null,
            "action" : " ",
            "fullAction" : null,
            "status" : "IAC",
            "fullStatus" : "INVOICES ARE CURRENT",
            "desk" : "008",
            "deskName" : "DELL NT NEW BIZ",
            "noteSeqNo" : "000025",
            "dbr_no" : "0028396",
            "notes" : "Large Balance Fedex\n",
            "ltr_desc" : null,
            "ltr_code" : null,
            "dat_type" : "H"
          },
          {
            "date" : "2022-12-08 20:50",
            "user" : "EDI",
            "fullName" : null,
            "action" : "ANA",
            "fullAction" : "ADMIN NOTE ADDED",
            "status" : "IAC",
            "fullStatus" : "INVOICES ARE CURRENT",
            "desk" : "RP4",
            "deskName" : "Vivian Lopez",
            "noteSeqNo" : "000022",
            "dbr_no" : "0028396",
            "notes" : "Possible ties \n 8848072,7978990,7978927\n",
            "ltr_desc" : null,
            "ltr_code" : null,
            "dat_type" : "C"
          },
          {
            "date" : "2021-05-10 09:51",
            "user" : "EDI",
            "fullName" : null,
            "action" : "IAD",
            "fullAction" : "INVOICE ADDED TO ACCOUNT",
            "status" : "IAC",
            "fullStatus" : "INVOICES ARE CURRENT",
            "desk" : "RP4",
            "deskName" : "Vivian Lopez",
            "noteSeqNo" : "000019",
            "dbr_no" : "0028396",
            "notes" : "INVOICE 72206251: AMT: 21600.00 ADDED TO ACCOUNT.\n\n",
            "ltr_desc" : null,
            "ltr_code" : null,
            "dat_type" : "C"
          },
          {
            "date" : "2021-05-04 12:04",
            "user" : "mandy.fisher@dandsltd.com",
            "fullName" : null,
            "action" : " ",
            "fullAction" : null,
            "status" : "IAC",
            "fullStatus" : "INVOICES ARE CURRENT",
            "desk" : "RP4",
            "deskName" : "Vivian Lopez",
            "noteSeqNo" : "000016",
            "dbr_no" : "0028396",
            "notes" : "",
            "ltr_desc" : null,
            "ltr_code" : null,
            "dat_type" : "H"
          },
          {
            "date" : "2021-04-09 06:42",
            "user" : "EDI",
            "fullName" : null,
            "action" : " ",
            "fullAction" : null,
            "status" : "IAC",
            "fullStatus" : "INVOICES ARE CURRENT",
            "desk" : "RP2",
            "deskName" : "Stephanie Jones",
            "noteSeqNo" : "000013",
            "dbr_no" : "0028396",
            "notes" : "",
            "ltr_desc" : null,
            "ltr_code" : null,
            "dat_type" : "H"
          },
          {
            "date" : "2021-04-09 06:42",
            "user" : "EDI",
            "fullName" : null,
            "action" : "CHS",
            "fullAction" : "CHANGE STATUS",
            "status" : "IAC",
            "fullStatus" : "INVOICES ARE CURRENT",
            "desk" : "RCM",
            "deskName" : "Current desk WB, Veg, CP, Accl",
            "noteSeqNo" : "000010",
            "dbr_no" : "0028396",
            "notes" : "All invoices are current, status updated to IAC and desk updated to IAC desk.\n\n",
            "ltr_desc" : null,
            "ltr_code" : null,
            "dat_type" : "C"
          },
          {
            "date" : "2021-04-09 06:42",
            "user" : "EDI",
            "fullName" : null,
            "action" : " ",
            "fullAction" : null,
            "status" : "IAC",
            "fullStatus" : "INVOICES ARE CURRENT",
            "desk" : "RCM",
            "deskName" : "Current desk WB, Veg, CP, Accl",
            "noteSeqNo" : "000007",
            "dbr_no" : "0028396",
            "notes" : "",
            "ltr_desc" : null,
            "ltr_code" : null,
            "dat_type" : "S"
          },
          {
            "date" : "2021-04-08 09:09",
            "user" : "EDI",
            "fullName" : null,
            "action" : "IAD",
            "fullAction" : "INVOICE ADDED TO ACCOUNT",
            "status" : "NEW",
            "fullStatus" : "NEWLY PLACED ACCOUNT",
            "desk" : "RCM",
            "deskName" : "Current desk WB, Veg, CP, Accl",
            "noteSeqNo" : "000004",
            "dbr_no" : "0028396",
            "notes" : "INVOICE 72147415: AMT: 90463.50 ADDED TO ACCOUNT.\n\n",
            "ltr_desc" : null,
            "ltr_code" : null,
            "dat_type" : "C"
          },
          {
            "date" : "2021-04-08 09:07",
            "user" : "EDI",
            "fullName" : null,
            "action" : " ",
            "fullAction" : null,
            "status" : "NEW",
            "fullStatus" : "NEWLY PLACED ACCOUNT",
            "desk" : "RCM",
            "deskName" : "Current desk WB, Veg, CP, Accl",
            "noteSeqNo" : "000001",
            "dbr_no" : "0028396",
            "notes" : "",
            "ltr_desc" : null,
            "ltr_code" : null,
            "dat_type" : "A"
          }
        ]
    }
}

export default data;
